# Generated by Django 3.2.8 on 2022-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explist',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Travel', 'Travel'), ('Transportation', 'Transportation'), ('Insurance', 'Insurance'), ('Tution', 'Tution'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Health care', 'Health care')], default='Housing', max_length=100),
        ),
    ]
