# Generated by Django 3.2.8 on 2022-01-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elist', '0002_alter_explist_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explist',
            old_name='user_expense',
            new_name='expense_of',
        ),
        migrations.RenameField(
            model_name='inclist',
            old_name='user_income',
            new_name='income_of',
        ),
        migrations.AlterField(
            model_name='explist',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Travel', 'Travel'), ('Transportation', 'Transportation'), ('Insurance', 'Insurance'), ('Tution', 'Tution'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Health care', 'Health care'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inclist',
            name='source',
            field=models.CharField(choices=[('Job Salary', 'Job Salary'), ('Profit Sale', 'Profit Sale'), ('Profit Stock', 'Profit Stock'), ('Heist', 'Heist'), ('Treasure', 'Treasure'), ('Scam', 'Scam'), ('Other', 'Other')], max_length=100),
        ),
    ]
