# Generated by Django 3.2.8 on 2022-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclist',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
